### PR TITLE
Update kubernetes client.

### LINKED ISSUE #180: New kubernetes version (10.1.0) incompatible with PyYAML in tag 0.6.0
Hello,

On March 12, `kubernetes` released versions 10.1.0 to 11.0.0
https://pypi.org/project/kubernetes/#history

This is now installed by pip rather than 10.0.1. The problem is, we use PyYAML 5.3.1 and:
- Kubernetes 10.0.1 requires PyYAML >= 3.12
- Kubertenes 10.1.0 requires PyYAML ~= 3.12

Should we update tag 0.6.0 to use 10.0.1 explictly here?
https://github.com/reanahub/reana-commons/blob/v0.6.0/setup.py#L32

```
======
Collecting kubernetes==10.0.1
  Using cached kubernetes-10.0.1-py2.py3-none-any.whl (1.5 MB)
Collecting pyyaml>=3.12

======
But when I try 10.1.0 instead, I get:
====
Collecting kubernetes==10.1.0
 Using cached kubernetes-10.1.0.tar.gz (689 kB)
Collecting pyyaml~=3.12
====
```

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #180.
Updating kubernetes version. I did not change reana-commons version number [here](https://github.com/reanahub/reana-commons/blob/maint-0.6/reana_commons/version.py#L17) though, let me know if I should.

### CODE REVIEW

**Comment by diegodelemos** [comment]
Can you reproduce [the problem](https://travis-ci.org/github/reanahub/reana-commons/jobs/677391548) shown in Travis CI locally if you run `run-tests.sh`? Looks like the Kubernetes library is trying to load real configuration and connect, however, this shouldn't happen as we are always mocking this kind of behaviour.

**Comment by khurtado** [comment]
@diegodelemos I get the following instead:
```
(reana) [khurtado@khurtado-reanandvc3 reana-commons]$ sh run-tests.sh
ERROR: /home/khurtado/projects/src/reana/reana-commons/tests/test_mq.py Imports are incorrectly sorted.
--- /home/khurtado/projects/src/reana/reana-commons/tests/test_mq.py:before	2020-04-28 12:45:05.191935
+++ /home/khurtado/projects/src/reana/reana-commons/tests/test_mq.py:after	2020-04-28 12:58:43.022499
@@ -11,11 +11,11 @@
 import json
 import threading

-import pytest
 from kombu import Connection, Exchange, Queue
 from kombu.exceptions import OperationalError
+
+import pytest
 from mock import ANY, patch
-
 from reana_commons.publisher import WorkflowStatusPublisher


ERROR: /home/khurtado/projects/src/reana/reana-commons/tests/test_secrets_store.py Imports are incorrectly sorted.
--- /home/khurtado/projects/src/reana/reana-commons/tests/test_secrets_store.py:before	2020-04-28 12:45:05.191935
+++ /home/khurtado/projects/src/reana/reana-commons/tests/test_secrets_store.py:after	2020-04-28 12:58:43.028761
@@ -8,11 +8,11 @@

 import json

-import pytest
 from kubernetes import client
 from kubernetes.client.rest import ApiException
+
+import pytest
 from mock import DEFAULT, Mock, patch
-
 from reana_commons.errors import (REANASecretAlreadyExists,
                                   REANASecretDoesNotExist)
 from reana_commons.k8s.secrets import REANAUserSecretsStore
ERROR: /home/khurtado/projects/src/reana/reana-commons/tests/test_tasks.py Imports are incorrectly sorted.
--- /home/khurtado/projects/src/reana/reana-commons/tests/test_tasks.py:before	2020-04-28 12:45:05.191935
+++ /home/khurtado/projects/src/reana/reana-commons/tests/test_tasks.py:after	2020-04-28 12:58:43.032640
@@ -9,7 +9,6 @@
 """REANA-Commons Task tests."""

 from mock import patch
-
 from reana_commons.tasks import reana_ready


ERROR: /home/khurtado/projects/src/reana/reana-commons/tests/test_utils.py Imports are incorrectly sorted.
--- /home/khurtado/projects/src/reana/reana-commons/tests/test_utils.py:before	2020-04-28 12:45:05.191935
+++ /home/khurtado/projects/src/reana/reana-commons/tests/test_utils.py:after	2020-04-28 12:58:43.040946
@@ -14,7 +14,6 @@

 from pytest import raises
 from pytest_reana.fixtures import sample_workflow_workspace
-
 from reana_commons.utils import (calculate_file_access_time,
                                  calculate_hash_of_dir,
                                  calculate_job_input_hash, click_table_printer,
```

**Comment by khurtado** [comment]
Hi @diegodelemos , just touching base on this. Did you get the chance to look into this (i.e.: making sure you don't see any errors either and this is a travis thing)?

**Comment by khurtado** [comment]
Hi @diegodelemos , I forgot about this issue, just pinging about it. Let us know if it's okay to merge

**Comment by tiborsimko** [comment]
Hi @khurtado, the Travis CI was stuck, relaunching builds was OK. It was necessary to also amend several other repositories such as `r-server` and `r-cluster`, but REANA 0.6.0-dev is working now, so we'll get this merged soon.

**Comment by tiborsimko** [comment]
> It was necessary to also amend several other repositories such as r-server and r-cluster

Here are the PRs:

- https://github.com/reanahub/reana-commons/pull/187
- https://github.com/reanahub/reana-server/pull/247
- https://github.com/reanahub/reana-cluster/pull/265

**Pull request merged**
