### PR TITLE
global: fix typo

### PR DESCRIPTION
**Pull request by mvidalgarcia**
closes reanahub/reana#422

### CODE REVIEW

**Comment by tiborsimko** [comment]
Can you please look at the CI test troubles? I can reproduce locally:

```console
$ mkvirtualenv r-commons
$ pip install '.[all]'
...
ERROR: reana-db 0.8.0a5 has requirement reana-commons>=0.8.0a1, but you'll have reana-commons 0.7.0a6 which is incompatible.
ERROR: pytest-reana 0.7.0a1 has requirement mock<4.0,>=3.0, but you'll have mock 4.0.2 which is incompatible.
$ pip freeze | grep reana
pytest-reana==0.7.0a1
reana-commons @ file:///.../reana-commons
reana-db==0.8.0a5
```

We need a pin somewhere in the `tests_require` chain so as not to require 0.8.* for `maint-0.7` work... Probably here:

```
$ grep reana pytest-reana/setup.py | head -2
    "reana-commons[kubernetes]>=0.7.0.dev20200203",
    "reana-db>=0.7.0.dev20200206",
```

Can you try and make a new PR for `pytest-reana`'s `maint-0.7` branch? 

P.S. Do we need `reana-db` for running `reana-commons` tests? Perhaps we could make it an optional installation target in `pytest-reana`... Worrying about circular dependencies amongst `reana-commons`, `reana-db`, and `pytest-reana`.

**Comment by mvidalgarcia** [comment]
> P.S. Do we need `reana-db` for running `reana-commons` tests? Perhaps we could make it an optional installation target in `pytest-reana`... Worrying about circular dependencies amongst `reana-commons`, `reana-db`, and `pytest-reana`.

I see there are some fixtures being used in `reana-commons` tests that come from files that have `reana-db` imports. So might be needed, but I'm not completely sure.

**Comment by mvidalgarcia** [comment]
Tests passing locally installing [this PR](https://github.com/reanahub/pytest-reana/pull/67). ✅

**Comment by tiborsimko** [comment]
> I see there are some fixtures being used in `reana-commons` tests that come from files that have `reana-db` imports. So might be needed, but I'm not completely sure.

@diegodelemos Have you been working on making DB imports "localised" for the master branch? Something w could easily backport to `maint-0.7` ? Or shall we create `pip install pytest-reana[db]` so that they are only installed on demand?

Anyway, if pinning helped, then we are also good to do it later... We'd need to keep the `0.7.*` pins in all cases...

**Comment by tiborsimko** [comment]
> Tests passing locally installing [this PR](https://github.com/reanahub/pytest-reana/pull/67). white_check_mark

`pytest-reana 0.7.0a2` is now released on PyPI, can you please bump the version in the PR set and repush?

**Review by tiborsimko — APPROVED** [review]

**Pull request merged**
