### PR TITLE
ci: added flake8 linter

### PR DESCRIPTION
**Pull request by audrium**
addresses https://github.com/reanahub/reana/issues/456

### CODE REVIEW

**Comment by audrium** [comment]
Tests are not passing because of the same [directory hash mismatch issue](https://github.com/reanahub/reana-commons/issues/238)

Having the fact that it's not passing on `ubuntu-18.04` as well, I've changed GA tests to run on `ubuntu-20.04`, since it was not the reason for tests to fail.

**Comment by mvidalgarcia** [comment]
I confirm that tests fail on my repo as well: https://github.com/mvidalgarcia/reana-commons/runs/1423771695

**Comment by audrium** [comment]
I can reproduce it also on my laptop

**Comment by mvidalgarcia** [comment]
I think this was fixed on `master` but not on `maint-0.7`, my bad: https://github.com/reanahub/reana-commons/commit/95a719b6bb67b7d981860018e0a8c509a8d1d54e
I'll take care ✋

**Review by mvidalgarcia — APPROVED** [review]

**Pull request merged**
